### ISSUE TITLE
Is there a way to shorten the time between putting the proxy link in and the website showing up?

### ISSUE THREAD

**Issue by CoolPerson879** [Tacogamerman/Sword-Games#7]
The time between entering the link and it showing up is way too long. Even on gigabit speed ethernet, it is way too slow, and sometimes it lags inside the proxy, although I don't think this a a problem with the proxy or latency. Is there any way to fix this?

**Comment by Tacogamerman** [comment]
Nah you can fork and change it to ultraviolet if you want
